#!/usr/bin/env python3
"""Assemble Figure 1 as a 2-row × 6-column PCA3 image grid.

Rows are locations and columns are embedding systems. The input panels are the
clean, native-resolution PNGs generated by figure1_generate_panels.py.
"""
from __future__ import annotations

import argparse
import os
from pathlib import Path

import matplotlib.pyplot as plt
from PIL import Image


SCRATCH_ROOT = Path(
    os.environ.get("FIGURE1_SCRATCH_ROOT", "/scratch/users/nhendrix/embeddings-health")
)
PANEL_ROOT = Path(
    os.environ.get(
        "FIGURE1_PANEL_ROOT",
        str(SCRATCH_ROOT / "figures" / "figure1_panels"),
    )
)
OUTPUT_ROOT = Path(
    os.environ.get("FIGURE1_OUTPUT_ROOT", str(SCRATCH_ROOT / "figures"))
)

MODELS = (
    ("alphaearth_foundations", "AlphaEarth\nFoundations"),
    ("olmoearth_v1_2_nano", "OlmoEarth v1.2\nNano"),
    ("olmoearth_v1_2_base", "OlmoEarth v1.2\nBase"),
    ("clay_v1_5", "Clay\nv1.5"),
    ("prithvi_eo_2_tiny_tl", "Prithvi-EO-2.0\ntiny-TL"),
    ("prithvi_eo_2_300m_tl", "Prithvi-EO-2.0\n300M-TL"),
)

LOCATIONS = (
    ("palo_alto", "Palo Alto,\nCA"),
    ("washington_dc", "Washington,\nDC"),
)


def panel_path(location_key: str, model_key: str) -> Path:
    return PANEL_ROOT / location_key / f"{model_key}_pca3.png"


def assemble(output_stem: Path, dpi: int = 320) -> list[Path]:
    missing = [
        panel_path(location_key, model_key)
        for location_key, _ in LOCATIONS
        for model_key, _ in MODELS
        if not panel_path(location_key, model_key).is_file()
    ]
    if missing:
        raise FileNotFoundError(
            "Missing Figure 1 panels:\n" + "\n".join(f"  {path}" for path in missing)
        )

    plt.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "font.size": 11,
            "axes.titleweight": "semibold",
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )

    fig = plt.figure(figsize=(15.6, 5.45), facecolor="white")
    grid = fig.add_gridspec(
        nrows=2,
        ncols=7,
        width_ratios=(0.58, 1, 1, 1, 1, 1, 1),
        height_ratios=(1, 1),
        left=0.018,
        right=0.995,
        bottom=0.035,
        top=0.865,
        wspace=0.025,
        hspace=0.035,
    )

    image_axes = []
    for row, (location_key, location_label) in enumerate(LOCATIONS):
        label_axis = fig.add_subplot(grid[row, 0])
        label_axis.set_axis_off()
        label_axis.text(
            0.96,
            0.5,
            location_label,
            ha="right",
            va="center",
            fontsize=13,
            fontweight="semibold",
            color="#1f1f1f",
            linespacing=1.25,
        )

        row_axes = []
        for col, (model_key, model_label) in enumerate(MODELS):
            axis = fig.add_subplot(grid[row, col + 1])
            with Image.open(panel_path(location_key, model_key)) as image:
                axis.imshow(image.convert("RGB"), interpolation="nearest")

            axis.set_xticks([])
            axis.set_yticks([])
            axis.set_aspect("equal")
            for spine in axis.spines.values():
                spine.set_visible(True)
                spine.set_color("#333333")
                spine.set_linewidth(0.55)

            if row == 0:
                axis.set_title(
                    model_label,
                    fontsize=11.5,
                    pad=10,
                    color="#161616",
                    linespacing=1.12,
                )
            row_axes.append(axis)
        image_axes.append(row_axes)

    output_stem.parent.mkdir(parents=True, exist_ok=True)
    outputs = [
        output_stem.with_suffix(".png"),
        output_stem.with_suffix(".pdf"),
        output_stem.with_suffix(".svg"),
    ]
    fig.savefig(
        outputs[0],
        dpi=dpi,
        facecolor="white",
        bbox_inches=None,
        pad_inches=0,
    )
    fig.savefig(
        outputs[1],
        dpi=dpi,
        facecolor="white",
        bbox_inches=None,
        pad_inches=0,
    )
    fig.savefig(
        outputs[2],
        dpi=dpi,
        facecolor="white",
        bbox_inches=None,
        pad_inches=0,
    )

    preview = output_stem.with_name(f"{output_stem.name}_preview").with_suffix(".png")
    fig.savefig(
        preview,
        dpi=120,
        facecolor="white",
        bbox_inches=None,
        pad_inches=0,
    )
    outputs.append(preview)
    plt.close(fig)

    for output in outputs:
        print(output)
    return outputs


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-stem",
        type=Path,
        default=OUTPUT_ROOT / "figure1_embedding_pca3_2x6",
        help="Output path without extension",
    )
    parser.add_argument("--dpi", type=int, default=320)
    args = parser.parse_args()
    assemble(args.output_stem, dpi=args.dpi)


if __name__ == "__main__":
    main()
